# Design port used
# Report 8081:1337
# PDF 8084:1337
# API  8082:80
# SRS API 8083:80
# Mysql 33062:3306


# Mysql
vita-mysql:
  image: mysql:5.6
  container_name: vita-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=Cloud@Interactive#
    - MYSQL_DATABASE=report_management
    - MYSQL_USER=cloud
    - MYSQL_PASSWORD=Cloud@1234#
  ports:
    - "33062:3306"
  volumes:
    - ../docker-data/mysql:/var/lib/mysql


# SRS API
srsapi-nginx:
  image: phpdockerio/nginx:latest
  container_name: srsapi-nginx
  volumes:
    - ../site/srsapi:/var/www/srsapi
    - ./srsapi/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "8083:80"
  links:
    - srsapi-php-fpm

srsapi-php-fpm:
  build: .
  dockerfile: srsapi/php-fpm/Dockerfile
  container_name: srsapi-php-fpm
  volumes:
    - ../site/srsapi:/var/www/srsapi
    - ./srsapi/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - vita-mysql


# API
api-nginx:
  image: phpdockerio/nginx:latest
  container_name: api-nginx
  volumes:
      - ../site/api:/var/www/api
      - ./api/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
  - "8082:80"
  links:
  - api-php-fpm

api-php-fpm:
  build: .
  dockerfile: api/php-fpm/Dockerfile
  container_name: api-php-fpm
  volumes:
    - ../site/api:/var/www/api
    - ./api/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - vita-mysql
